apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service
  labels:
    app: fastapi-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-service
  template:
    metadata:
      labels:
        app: fastapi-service
    spec:
      containers:
      - name: fastapi-container
        image: us-central1-docker.pkg.dev/prueba-servicios-446022/pruebarepo/humblecoop-service:v2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /v1/healthz/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20 
        readinessProbe:
          httpGet:
            path: /v1/healthz/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /v1/healthz/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30